# Generated by Django 6.1.1 on 2026-09-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Веедите ваше имя", max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(help_text="Веедите почту", max_length=254, verbose_name="Почта")),
                ("message", models.TextField(help_text="Веедите ваше сообщение", verbose_name="Сообщение")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото продукта",
                null=True,
                upload_to="catalog/photo",
                verbose_name="Фото",
            ),
        ),
    ]
